var bd = [
	{
	"Name": "135 Neville Anti-Tank Rifle",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/1/1f/Anti-Tank_Rifle.png",
	"Encumbrance": 38,
	"Slot": 1,
	"Stackable": false,
	"Class": "Anti-Tank Rifle",
	"Ammo": "13.5mm",
	"Type": "Anti-Tank Kinetic",
	"Faction": "Warden",
	"Description": "The Neville is unmatched in its versatility as a portable, magazine-based anti-armour firearm.",
	},
	{
	"Name": "Aalto Storm Rifle 24",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/21/StormRifle.png",
	"Encumbrance": 27,
	"Slot": 1,
	"Stackable": false,
	"Class": "Assault Rifle",
	"Ammo": "7.92mm",
	"Type": "Light Kinetic",
	"Faction": "Warden",
	"Description": "Widely considered to be the first storm rifle, the Aalto is a marvel in Caoivish engineering. With its two fire modes, it can be used as a rapid-fire assault weapon, or an mid-range rifle.",
	},
	{
	"Name": "Catara mo.II",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/f/f2/LightMachineGunIcon.png",
	"Encumbrance": 32,
	"Slot": 1,
	"Stackable": false,
	"Class": "Assault Rifle",
	"Ammo": "7.92mm",
	"Type": "Light Kinetic",
	"Faction": "Colonial",
	"Description": "A titanic light machine gun capable of scattering infantry lines with ease, the Catara is a modern weapon for the modern colonial.",
	},
	{
	"Name": "Daucus isg.III",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/5/5d/Daucus_isg_Icon.png",
	"Encumbrance": 54,
	"Slot": 8,
	"Stackable": false,
	"Class": "Infantry Support Gun",
	"Ammo": "30mm",
	"Type": "Explosive",
	"Faction": "Colonial",
	"Description": "This heavy infantry cannon requires a tripod for stability. The Daucus is designed to give infantry a foothold against enemy vehicles and light fortifications or establish fortified garrisons.",
	},
	{
	"Name": "Malone MK.2",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/5/52/Malone_MG_Icon.png",
	"Encumbrance": 36,
	"Slot": 1,
	"Stackable": false,
	"Class": "Machine Gun",
	"Ammo": "12.7mm",
	"Type": "Heavy Kinetic",
	"Faction": "Warden",
	"Description": "This heavy machine gun is bulky enough to require a steady surface to maintain stability. The Malone series of machine guns are unmatched defenders on the battlefield.",
	},
	{
	"Name": "KRN886-127 Gast Machine Gun",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/8/8e/Gast_MG_Icon.png",
	"Encumbrance": 36,
	"Slot": 1,
	"Stackable": false,
	"Class": "Machine Gun",
	"Ammo": "12.7mm",
	"Type": "Heavy Kinetic",
	"Faction": "Colonial",
	"Description": "The Gast is a deadly but cumbersome Kraunian heavy machine gun. It is best suited to holding and defending established fortifications or garrisoned structures against encroaching infantry.",
	},
	{
	"Name": "Ferro 879",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/b/bb/Pistol-0.png",
	"Encumbrance": 9,
	"Slot": 2,
	"Stackable": false,
	"Class": "Pistol",
	"Ammo": "8mm",
	"Type": "Light Kinetic",
	"Description": "A pistol imported from Estrella in the east, the Ferro 879 is a common sight on many battlefields.",
	},
	{
	"Name": "Cascadier 873",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/4/4c/Burst_Pistol_Icon.png",
	"Encumbrance": 7,
	"Slot": 2,
	"Stackable": false,
	"Class": "Pistol",
	"Ammo": "8mm",
	"Type": "Light Kinetic",
	"Faction": "Warden",
	"Description": "This unique sidearm fires in three-round bursts. The Cascadier may not have the stopping power of its cousins, but it more than make sup for it with its lightweight frame, concealability, and fire rate.",
	},
	{
	"Name": "Cometa T2-9",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/6/6d/Revolver.png",
	"Encumbrance": 13,
	"Slot": 2,
	"Stackable": false,
	"Class": "Revolver",
	"Ammo": ".44",
	"Type": "Light Kinetic",
	"Description": "The Cometa T2-9 boasts remarkable stopping power for a sidearm. This Estrellan mainstay has lived through several generations due to its fine craftsmanship and design.",
	},
	{
	"Name": "No.2 Loughcaster",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/9/9f/Rifle.png",
	"Encumbrance": 18,
	"Slot": 1,
	"Stackable": false,
	"Class": "Rifle",
	"Ammo": "7.62mm",
	"Type": "Light Kinetic",
	"Faction": "Warden",
	"Description": "Standard-issue Warden rifle. This bolt-action firearm is as robust as they come and has seen over a century of use on the battlefield.",
	},
	{
	"Name": "Argenti r.II Rifle",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/f/f2/Argenti_Rifle_Icon.png",
	"Encumbrance": 12,
	"Slot": 1,
	"Stackable": false,
	"Class": "Rifle",
	"Ammo": "7.62mm",
	"Type": "Light Kinetic",
	"Faction": "Colonial",
	"Description": "The primary infantry rifle of the Colonial Legion. Its predecessor, The Volta Repeater, was a sturdy, reliable firearm but had many limitations, namely, fire rate. The Argenti solves this limitation as well as being more compact and lightweight.",
	},
	{
	"Name": "Blakerow 871",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/b/b6/Carabine.png",
	"Encumbrance": 12,
	"Slot": 1,
	"Stackable": false,
	"Class": "Rifle",
	"Ammo": "7.62mm",
	"Type": "Light Kinetic",
	"Faction": "Warden",
	"Description": "The Blakerow is a carbine with a high rate of fire compared to its bolt-action predecessor. This increased fire rate does come at the cost of innate stopping power; however, its versatility and lightweight frame more than make up for any perceived shortcomings.",
	},
	{
	"Name": "Fuscina pi.I",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/73/Fuscina_Rifle_Icon.png",
	"Encumbrance": 18,
	"Slot": 1,
	"Stackable": false,
	"Class": "Rifle",
	"Ammo": "7.62mm",
	"Type": "Light Kinetic",
	"Faction": "Colonial",
	"Description": "This unique rifle fires three rounds in rapid succession. The Fuscina is the first of its kind, designed for laying down suppressive fire during assaults on fortified enemy entrenchments.",
	},
	{
	"Name": "Fiddler Submachine Gun Model 868",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/e/e5/Smg-1.png",
	"Encumbrance": 14,
	"Slot": 1,
	"Stackable": false,
	"Class": "SMG",
	"Ammo": "9mm SMG",
	"Type": "Light Kinetic",
	"Faction": "Warden",
	"Description": "The Fiddler Submachine gun is a widely used urban combat weapon. Its high rate of fire and compact frame make it ideal for close-quarters engagements.",
	},
	{
	"Name": "'The Pitch Gun' mc.V",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/d/d5/Pitch_Gun_Icon.png",
	"Encumbrance": 14,
	"Slot": 2,
	"Stackable": false,
	"Class": "SMG",
	"Ammo": "9mm SMG",
	"Type": "Light Kinetic",
	"Faction": "Colonial",
	"Description": "This classic submachine gun is sturdy and irreplacable as a general tool for close-range engagements. The Pitch Gun earned its namesake from Mesean sailors who employed the weapon to successfully defend against a night raid on the Geraston docks.",
	},
	{
	"Name": "Brasa Shotgun",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/6/61/Shotgun.png",
	"Encumbrance": 15,
	"Slot": 1,
	"Stackable": false,
	"Class": "Shotgun",
	"Ammo": "Buckshot",
	"Type": "Light Kinetic",
	},
	{
	"Name": "Clancy-Raca M4",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/3/30/SniperRifleItemIcon.png",
	"Encumbrance": 37,
	"Slot": 1,
	"Stackable": false,
	"Class": "Sniper Rifle",
	"Ammo": "8.5mm",
	"Type": "Light Kinetic",
	"Faction": "Warden",
	"Description": "A heavy-duty, long-range marksman rifle. The Clancy-Raca has one hell of a kick but is fitted with a powerful scope, allowing infantry to survey the battlefield and provide support from a safe location.",
	},
	{
	"Name": "KRR3-792 Auger",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/f/f2/Auger_Sniper_Icon.png",
	"Encumbrance": 22,
	"Slot": 1,
	"Stackable": false,
	"Class": "Sniper Rifle",
	"Ammo": "8.5mm",
	"Type": "Light Kinetic",
	"Faction": "Colonial",
	"Description": "A Kraunian rifle modified for long-range engagements. It doesn’t have the range or stopping power of other marksman rifles but more than makes up for it with unmatched reliability in a range of environments and a superior effective rate of fire.",
	},
	{
	"Name": "Abisme AT-99",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/3/37/Land_Mine.png",
	"Encumbrance": 7,
	"Slot": 3,
	"Stackable": false,
	"Class": "Anti-Tank Mine",
	"Type": "Anti-Tank Explosive",
	"Description": "A simple mine that is placed under terrain and fitted with a pressure-sensitive plate to detonate under the weight of heavy vehicles. Mines are visible to friendlies and enemies on foot. Mines deactivate after 48 in-game days.",
	},
	{
	"Name": "Anti-Tank Sticky Bomb",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/74/Sticky_Bomb.png",
	"Encumbrance": 18,
	"Slot": 3,
	"Stackable": false,
	"Class": "Anti-Tank Sticky Bomb",
	"Type": "Anti-Tank Explosive",
	"Description": "An adherable grenade designed to penetrate heavy tank armor. The Sticky Bomb can only be thrown a short distance and is ineffective against structures.",
	},
	{
	"Name": "Green Ash Grenade",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/d/d6/Green_Ash.png",
	"Encumbrance": 3,
	"Slot": 3,
	"Stackable": false,
	"Class": "Gas Grenade",
	"Type": "Poisonous Gas",
	"Description": "A thrown canister full of poisonous gas.",
	},
	{
	"Name": "A3 Harpa Fragmentation Grenade",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/f/fb/Grenade.png",
	"Encumbrance": 3,
	"Slot": 3,
	"Stackable": false,
	"Class": "Grenade",
	"Type": "Light Kinetic",
	"Faction": "Warden",
	"Description": "This anti-personnel fragmentation grenade is designed with pull-pin mechanics and a timed fuse for user safety. Serrations in the casing allow for a better grip and increased fragmentation effectiveness.",
	},
	{
	"Name": "Bomastone Grenade",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/2e/Bomastone_Grenade_Icon.png",
	"Encumbrance": 3,
	"Slot": 3,
	"Stackable": false,
	"Class": "Grenade",
	"Type": "Shrapnel",
	"Faction": "Colonial",
	"Description": "The Bomastone is a 'stick' style fragmentation grenade with a handle designed to aid in lobbing over moderate distances.",
	},
	{
	"Name": "Mammon 91-b",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/6/6b/HE_Grenade.png",
	"Encumbrance": 14,
	"Slot": 3,
	"Stackable": false,
	"Class": "High Explosive Grenade",
	"Type": "Explosive",
	"Description": "This densely packed, high-explosive grenade is designed to damage structures and vehicles.",
	},
	{
	"Name": "Alligator Charge",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/6/6f/Satchel_Chrg.png",
	"Encumbrance": 36,
	"Slot": 3,
	"Stackable": false,
	"Class": "Satchel Charge",
	"Type": "Demolition",
	"Description": "This heavy-duty explosive device is designed to deal significant damage to structures and stationary vehicles.",
	},
	{
	"Name": "PT-815 Smoke Grenade",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/5/51/Smk_Grenade.png",
	"Encumbrance": 4,
	"Slot": 3,
	"Stackable": false,
	"Class": "Smoke Grenade",
	"Description": "A thrown projectile that emits smoke, blocking visibility.",
	},
	{
	"Name": "Bonesaw MK.3",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/70/Bonesaw_Icon.png",
	"Encumbrance": 54,
	"Slot": 1,
	"Stackable": false,
	"Class": "Anti-Tank RPG",
	"Ammo": "A.T.R.P.G. Indirect Shell",
	"Type": "Armour Piercing",
	"Faction": "Warden",
	"Description": "The pride of the Warden anti-armour arsenal, the Bonesaw MK.3 has one job: to cut through the heavy metal plating of Colonial tanks.",
	},
	{
	"Name": "Mounted Bonesaw MK.3",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/e/e4/Mounted_Bonesaw_Icon.png",
	"Encumbrance": 54,
	"Slot": 8,
	"Stackable": false,
	"Class": "Anti-Tank RPG",
	"Ammo": "A.T.R.P.G. Indirect Shell",
	"Type": "Armour Piercing",
	"Faction": "Warden",
	"Description": "This variant of the Bonesaw MK.3 is specially designed for use with tripod mounts. This affords it with increased stability and maximum potential range.",
	},
	{
	"Name": "Ignifist 30",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/1/11/Ignifist_Icon.png",
	"Encumbrance": 21.8,
	"Slot": 1,
	"Stackable": false,
	"Class": "Anti-Tank RPG",
	"Ammo": "N/A",
	"Type": "Armour Piercing",
	"Faction": "Colonial",
	"Description": "This single-use rocket can be fired a short distance. Designed to punch holes into tanks, the Ignifist is the perfect tool for infantry anticipating armoured resistance.",
	},
	{
	"Name": "Venom c.II 35",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/c/cd/Venom_c.II_Icon.png",
	"Encumbrance": 54,
	"Slot": 1,
	"Stackable": false,
	"Class": "Anti-Tank RPG",
	"Ammo": "A.T.R.P.G. Shell",
	"Type": "Armour Piercing",
	"Faction": "Colonial",
	"Description": "The Venom RPG launcher fires anti-tank charges. Its simple design makes it easy to deploy, even in high-stakes operations.",
	},
	{
	"Name": "Bane 45",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/d/d3/Bane_45_Icon.png",
	"Encumbrance": 54,
	"Slot": 1,
	"Stackable": false,
	"Class": "Anti-Tank RPG",
	"Ammo": "A.T.R.P.G. Shell",
	"Type": "Armour Piercing",
	"Faction": "Colonial",
	"Description": "This shoulder-mounted heavy launcher is the first of its kind. It features heavy blast shielding and is capable of launching anti-tank charges over relatively large distances.",
	},
	{
	"Name": "Cremari Mortar",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/f/f5/Mortar-0.png",
	"Encumbrance": 55,
	"Slot": 1,
	"Stackable": false,
	"Class": "Mortar",
	"Ammo": "Mortar Shell",
	"Description": "A short distance cannon used to take out infantry and lightly armored structures.",
	},
	{
	"Name": "Cutler Launcher 4",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/a/a5/Cutler_Launcher_Icon.png",
	"Encumbrance": 45,
	"Slot": 1,
	"Stackable": false,
	"Class": "R.P.G.",
	"Ammo": "R.P.G. Shell",
	"Type": "Explosive",
	"Faction": "Warden",
	"Description": "The Cutler Launcher is capable of firing an unguided, rocket-propelled grenade over short distances with startling efficiency. Its simple design allows for easy deployment and storage.",
	},
	{
	"Name": "Buckhorn CCQ-18",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/c/cd/Bayonet.png",
	"Encumbrance": 2,
	"Slot": 7,
	"Stackable": false,
	"Class": "Bayonet",
	},
	{
	"Name": ".44",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/26/.44.png",
	"Encumbrance": 1.8,
	"Slot": 0,
	"Stackable": true,
	"Type": "Light Kinetic",
	"Description": "Standard ammunition for revolvers.",
	},
	{
	"Name": "12.7mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/6/6c/127mm.png",
	"Encumbrance": 1.8,
	"Slot": 0,
	"Stackable": false,
	"Type": "Heavy Kinetic",
	"Description": "Standard ammunition for all machine guns, including vehicle mounted weapons likes those on Half-Track and Battle Tank.",
	},
	{
	"Name": "13.5mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/73/ATRifleAmmoItemIcon.png",
	"Encumbrance": 2.0,
	"Slot": 0,
	"Stackable": true,
	"Type": "Anti-Tank Kinetic",
	"Description": "Standard ammunition for anti-tank rifles.",
	},
	{
	"Name": "14.5mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/22/14.5mm.png",
	"Encumbrance": 9.1,
	"Type": "Heavy Kinetic",
	"Description": "Standard ammunition for Field Machine Guns and Gunboats.",
	},
	{
	"Name": "7.62mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/2d/762mm.png",
	"Encumbrance": 1.8,
	"Slot": 0,
	"Stackable": true,
	"Type": "Light Kinetic",
	"Description": "Standard ammunition for rifles.",
	},
	{
	"Name": "7.92mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/0/0c/7.92mmv1.png",
	"Encumbrance": 1.8,
	"Slot": 0,
	"Stackable": true,
	"Type": "Light Kinetic",
	"Description": "Standard ammunition for Storm Rifles, Light Machine Guns, and Armored Cars.",
	},
	{
	"Name": "8.5mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/2b/SniperRifleAmmoItemIcon.png",
	"Encumbrance": 2,
	"Slot": 0,
	"Stackable": true,
	"Type": "Light Kinetic",
	"Description": "Standard ammunition for sniper rifles.",
	},
	{
	"Name": "8mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/74/9mm.png",
	"Encumbrance": 1.8,
	"Slot": 0,
	"Stackable": true,
	"Type": "Light Kinetic",
	"Description": "Standard ammunition for pistols.",
	},
	{
	"Name": "9mm SMG",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/1/18/9mm_SMG.png",
	"Encumbrance": 1.8,
	"Slot": 0,
	"Stackable": true,
	"Type": "Light Kinetic",
	"Description": "Standard ammunition for submachine gun.",
	},
	{
	"Name": "Buckshot",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/c/c2/Buckshot.png",
	"Encumbrance": 1.8,
	"Slot": 0,
	"Stackable": true,
	"Type": "Light Kinetic",
	"Description": "Standard ammunition for Shotguns.",
	},
	{
	"Name": "120mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/6/6b/Howitzer_Shell.png",
	"Encumbrance": 45,
	"Slot": 0,
	"Stackable": false,
	"Type": "High Explosive",
	"Description": "Payload for light artillery weapons.",
	},
	{
	"Name": "150mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/e/e6/150mm.png",
	"Encumbrance": 54,
	"Slot": 8,
	"Stackable": false,
	"Type": "High Explosive",
	"Description": "Payload for heavy artillery weapons.",
	},
	{
	"Name": "250mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/77/250mm.png",
	"Encumbrance": 54,
	"Slot": 0,
	"Stackable": false,
	"Type": "Demolition",
	"Description": "A shell that is launched over short distances by a spigot mortar.",
	},
	{
	"Name": "300mm Round",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/8/8f/LRArtilleryAmmoItemIcon.png",
	"Encumbrance": 72,
	"Slot": 0,
	"Stackable": false,
	"Type": "Demolition",
	"Description": "Payload for the Storm Cannon.",
	},
	{
	"Name": "30mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/c/c8/30mm.png",
	"Encumbrance": 9.2,
	"Slot": 0,
	"Stackable": false,
	"Type": "Explosive",
	"Description": "Standard explosive shell for small vehicles or infantry weapons.",
	},
	{
	"Name": "40mm",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/70/LightTank_Ammo.png",
	"Encumbrance": 18.2,
	"Slot": 0,
	"Stackable": false,
	"Type": "Explosive",
	"Description": "Standard payload for light tanks.",
	},
	{
	"Name": "68mm AT",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/d/d2/68mm.png",
	"Encumbrance": 18.2,
	"Slot": 0,
	"Stackable": false,
	"Type": "Armour Piercing",
	"Description": "An Anti-Tank shell thats effective against penetrating tank armour.",
	},
	{
	"Name": "A.T.R.P.G. Indirect Shell",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/6/6b/ATRPG_Indirect_shell.png",
	"Encumbrance": 8.1,
	"Slot": 0,
	"Stackable": false,
	"Type": "Armour Piercing",
	"Description": "An anti-tank projectile fired from indirect R.P.G. weapons.",
	},
	{
	"Name": "A.T.R.P.G. Shell",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/2f/ATRPG_Shell.png",
	"Encumbrance": 8.1,
	"Slot": 0,
	"Stackable": false,
	"Type": "Armour Piercing",
	"Description": "An anti-tank projectile fired from an R.P.G.",
	},
	{
	"Name": "Mortar Shell",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/9/9f/Mortar_Shell.png",
	"Encumbrance": 7.25,
	"Slot": 0,
	"Stackable": false,
	"Type": "High Explosive",
	"Description": "An explosive projectile fired from a mortar.",
	},
	{
	"Name": "R.P.G. Shell",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/a/a2/RPG_shell_.png",
	"Encumbrance": 3.75,
	"Slot": 0,
	"Stackable": false,
	"Type": "Explosive",
	"Description": "An explosive projectile fired from an R.P.G.",
	},
	{
	"Name": "Hammer",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/8/81/Hammer.png",
	"Encumbrance": 4,
	"Slot": 1,
	"Stackable": false,
	"Description": "A tool used to build structures and assemble materials.",
	},
	{
	"Name": "Sledge Hammer",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/5/59/Sledge_Hammer.png",
	"Encumbrance": 18,
	"Slot": 1,
	"Stackable": false,
	"Description": "A tool used to salvage components from remains of old vehicles and equipment.",
	},
	{
	"Name": "Wrench",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/7c/Wrench.png",
	"Encumbrance": 5,
	"Slot": 1,
	"Stackable": false,
	"Description": "A multipurpose tool. Can be used to dismantle mines/barbed wire and unlock vehicles.",
	},
	{
	"Name": "Binoculars",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/7/74/Binoculars.png",
	"Encumbrance": 2,
	"Slot": 2,
	"Stackable": false,
	"Description": "An optical instrument used for viewing distant objects.",
	},
	{
	"Name": "Shovel",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/22/ShovelIcon.png",
	"Encumbrance": 19,
	"Slot": 1,
	"Stackable": false,
	"Description": "A tool for digging Trenches and other entrenched structures.",
	},
	{
	"Name": "Radio",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/3/31/Radio.png",
	"Encumbrance": 0.2,
	"Slot": 4,
	"Stackable": false,
	"Description": "A utility item that receives map intelligence updates.",
	},
	{
	"Name": "Radio Backpack",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/0/01/Radio_backpacks.png",
	"Encumbrance": 27,
	"Slot": 6,
	"Stackable": false,
	"Description": "Allows scouts to record map intel remotely. Press G to scout targets.",
	},
	{
	"Name": "Gas Mask",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/2/2e/Gas_Mask.png",
	"Encumbrance": 4,
	"Slot": 5,
	"Stackable": false,
	"Description": "Protects against poison gas.",
	},
	{
	"Name": "Gas Mask Filter",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/8/88/Gas_Mask_Filter_Icon.png",
	"Encumbrance": 4,
	"Stackable": false,
	"Description": "When attached to a Gas Mask, this filter provides fresh air to the wearer.",
	},
	{
	"Name": "Bandages",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/b/be/Bandages.png",
	"Encumbrance": 0.2,
	"Slot": 3,
	"Stackable": true,
	"Description": "Used to stem bleeding.",
	},
	{
	"Name": "First Aid Kit",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/9/9f/First_Aid_kit.png",
	"Encumbrance": 9,
	"Slot": 3,
	"Stackable": false,
	"Description": "Used by medics to heal others soldiers.",
	},
	{
	"Name": "Trauma Kit",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/d/d5/Trauma_Kit.png",
	"Encumbrance": 18,
	"Slot": 1,
	"Stackable": false,
	"Description": "Used by medics to revive wounded soldiers.",
	},
	{
	"Name": "Blood Plasma",
	"Icon": "https://static.wikia.nocookie.net/foxhole_gamepedia_en/images/f/ff/BloodPlasmaItemIcon.png",
	"Encumbrance": 0.33,
	"Stackable": false,
	"Description": "A blood component used to treat wounded soldiers on the battlefield.",
	},
];
